-- Jornada.pt - dados iniciais

insert into competitions (name, slug, country, logo_url, accent_color, is_active) values ('Premier League', 'premier-league', 'Inglaterra', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Premier_League.svg', '#ed1c24', true) on conflict (slug) do update set name = excluded.name, country = excluded.country, logo_url = excluded.logo_url, accent_color = excluded.accent_color, is_active = excluded.is_active;
insert into competitions (name, slug, country, logo_url, accent_color, is_active) values ('Liga Portugal', 'liga-portugal', 'Portugal', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Liga_Portugal.jpg', '#0f9b63', true) on conflict (slug) do update set name = excluded.name, country = excluded.country, logo_url = excluded.logo_url, accent_color = excluded.accent_color, is_active = excluded.is_active;
insert into competitions (name, slug, country, logo_url, accent_color, is_active) values ('La Liga', 'la-liga', 'Espanha', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/LaLiga_logo_(2023).svg', '#273f8f', true) on conflict (slug) do update set name = excluded.name, country = excluded.country, logo_url = excluded.logo_url, accent_color = excluded.accent_color, is_active = excluded.is_active;

insert into teams (name, short_name, slug, logo_url, primary_color) values ('Liverpool', 'LIV', 'liverpool', 'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg', 'red') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Chelsea', 'CHE', 'chelsea', 'https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg', 'blue') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Manchester City', 'MCI', 'manchester-city', 'https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg', 'sky') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Newcastle', 'NEW', 'newcastle', 'https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg', 'dark') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Arsenal', 'ARS', 'arsenal', 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg', 'red') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Tottenham', 'TOT', 'tottenham', 'https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg', 'navy') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Aston Villa', 'AVL', 'aston-villa', 'https://upload.wikimedia.org/wikipedia/en/9/9a/Aston_Villa_FC_new_crest.svg', 'claret') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Manchester United', 'MUN', 'manchester-united', 'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg', 'gold') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Brentford', 'BRE', 'brentford', 'https://upload.wikimedia.org/wikipedia/en/2/2a/Brentford_FC_crest.svg', 'stripe') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('West Ham', 'WHU', 'west-ham', 'https://upload.wikimedia.org/wikipedia/en/c/c2/West_Ham_United_FC_logo.svg', 'claret') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Brighton', 'BHA', 'brighton', 'https://upload.wikimedia.org/wikipedia/en/f/fd/Brighton_%26_Hove_Albion_logo.svg', 'blue') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Fulham', 'FUL', 'fulham', 'https://upload.wikimedia.org/wikipedia/en/e/eb/Fulham_FC_%28shield%29.svg', 'white') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Benfica', 'BEN', 'benfica', 'https://upload.wikimedia.org/wikipedia/en/a/a2/SL_Benfica_logo.svg', 'red') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('FC Porto', 'FCP', 'fc-porto', 'https://upload.wikimedia.org/wikipedia/en/f/f1/FC_Porto.svg', 'blue') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Sporting', 'SCP', 'sporting', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sporting_Clube_de_Portugal.svg', 'green') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Braga', 'BRA', 'braga', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sporting-clube-de-braga-vector-logo.png', 'red') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Real Madrid', 'RMA', 'real-madrid', 'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg', 'white') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Barcelona', 'BAR', 'barcelona', 'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg', 'navy') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Atlético Madrid', 'ATM', 'atletico-madrid', 'https://crests.football-data.org/78.svg', 'stripe') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;
insert into teams (name, short_name, slug, logo_url, primary_color) values ('Sevilla', 'SEV', 'sevilla', 'https://upload.wikimedia.org/wikipedia/en/3/3b/Sevilla_FC_logo.svg', 'red') on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, logo_url = excluded.logo_url, primary_color = excluded.primary_color;

insert into broadcast_channels (name, platform, country, logo_url) values ('Sport TV 1', 'Sport TV', 'Portugal', null);
insert into broadcast_channels (name, platform, country, logo_url) values ('Sport TV 2', 'Sport TV', 'Portugal', null);
insert into broadcast_channels (name, platform, country, logo_url) values ('Sport TV 3', 'Sport TV', 'Portugal', null);
insert into broadcast_channels (name, platform, country, logo_url) values ('DAZN 1', 'DAZN', 'Portugal', null);
