create index newsroom_mesa_material_versions_parent_version_idx on public.newsroom_mesa_material_versions(parent_version_id);
create index newsroom_mesa_material_versions_production_dossier_idx on public.newsroom_mesa_material_versions(production_dossier_id);
create index newsroom_mesa_material_versions_publication_event_idx on public.newsroom_mesa_material_versions(publication_event_id);
create index newsroom_mesa_production_contexts_theme_idx on public.newsroom_mesa_production_contexts(theme_id);
create index newsroom_mesa_theme_materials_material_version_idx on public.newsroom_mesa_theme_materials(material_key, version_id);
create index newsroom_mesa_version_article_refs_article_idx on public.newsroom_mesa_version_article_refs(editorial_article_id);
create index newsroom_mesa_version_source_refs_article_idx on public.newsroom_mesa_version_source_refs(newsroom_article_id);
create index newsroom_mesa_version_source_refs_snapshot_idx on public.newsroom_mesa_version_source_refs(newsroom_snapshot_id);
